title: <TITLE>
startUrl: <URL>
base: <URL>
favicon: <FAVICON>
target: _blank
hideVersion: true
showStats: true

headerStyle: boxed
background:
 image: https://images.unsplash.com/photo-1533134486753-c833f0ed4866
 opacity: 50
theme: dark
color: neutral
cardBlur: sm

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true

layout:
  Media:
    style: row
    columns: 4
  Downloaders:
    style: row
    columns: 3
  Utilities:
    style: row
    columns: 2
